### ISSUE TITLE
metal*drawing layers should be used for routing

### ISSUE THREAD

**Issue by proppy** [gdsfactory/skywater130#51]
Per https://github.com/gdsfactory/gdsfactory/issues/681#issuecomment-1367607941, `met*drawing` should be used for routing: https://github.com/gdsfactory/skywater130/blob/f537582f5fe4b6bf96ed6fad4d40ee3ee418740f/sky130/layers.py#L216 instead of the `:0` type which are reserved for production mask.

**Comment by joamatab** [comment]
fixed by https://github.com/gdsfactory/skywater130/pull/52
