### ISSUE TITLE
c.plot() doesn't keep the image window open 

### ISSUE THREAD

**Issue by saicharan0112** [gdsfactory/skywater130#57]
I was trying to implement the nmos pcell shown here - https://gdsfactory.github.io/skywater130/_autosummary/sky130.pcells.nmos.html. 
But while running the code from the command line with the "c.plot()" inside a script, I see that a window pops up but it doesn't stay and closes itself automatically. How do I keep the window open to view the layout?

**Comment by joamatab** [comment]
Hi Sai,

you can run `c.plot(blocking=True)`

**Comment by saicharan0112** [comment]
Thanks @joamatab, it worked!
